name: Code Style

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Validate composer files
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Check formatting with Pint
        run: composer pint:test
